In [89]:
import pandas as pd
import numpy as np

# x =  np.full((3,2),5.7) 
x=np.random.random((4,3))*100
x[1][1]=5435
x
np.savetxt('test.txt', x, delimiter=',')
y=np.loadtxt('test.txt', delimiter=',')
y.astype(np.int32)
y

array([[  66.38290711,   39.85202343,   68.03221933],
       [  94.36215437, 5435.        ,   63.32000439],
       [  38.79094504,   18.93983316,   90.782389  ],
       [  71.94166568,   44.39665923,   38.31860847]])

In [91]:
# np.exp(y)

np.sin([3.14/2])
z=np.eye(4)
z.dot(z)
y.sum()
y.sort()
y=y.reshape(6,-2)
y=np.hsplit(y,2)
y

[array([[39.85202343],
        [63.32000439],
        [94.36215437],
        [18.93983316],
        [38.31860847],
        [44.39665923]]),
 array([[  66.38290711],
        [  68.03221933],
        [5435.        ],
        [  38.79094504],
        [  90.782389  ],
        [  71.94166568]])]

In [32]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
